FROM golang:1.24-alpine as builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest
COPY --from=builder /go/bin/goose /usr/local/bin
WORKDIR /migrations
ENTRYPOINT ["goose"]